{{- if .Values.global.namespace.create }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "stream-sentinel.namespace" . }}
  labels:
    {{- include "stream-sentinel.labels" . | nindent 4 }}
{{- end }}
