apiVersion: v1
kind: Namespace
metadata:
  name: stream-sentinel
  labels:
    app.kubernetes.io/name: stream-sentinel
    app.kubernetes.io/part-of: stream-sentinel
    app.kubernetes.io/managed-by: kubectl
